---
functional:
  - пользователь должен иметь возможность создания пробной игры без регистрации
  - пользователь должен иметь возможность регистрации на сайте
  - пользователь должен иметь возможность регистрации на сайте
  - пользователь должен иметь возможность регистрации через email
  - пользователь должен иметь возможность регистрации и авторизации через Discord и Github
  - пользователь должен иметь возможность восстановить забытый пароль
  - пользователь должен иметь возможность создавать игру с ботом
  - пользователь должен иметь возможность создавать игру с другим пользователем
  - пользователь должен иметь возможность выбора уровня и продолжительности игры, типа задания
  - пользователь должен иметь возможность сдаться в игре
  - пользователь должен иметь возможность выбора языка программирования для написания кода в игре
  - пользователь должен иметь возможность создания турниров между пользователями
  - пользователь должен иметь возможность общения в общем чате игры
  - пользователь должен иметь возможность отправки личных сообщений другим пользователям
  - пользователь должен иметь возможность просмотра истории игры
  - пользователь должен иметь возможность просмотра и сортировки таблицы рейтингов пользователей
non-functional:
  - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен быть удобным на мобильном устройстве
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - все графические элементы сайта должны быть выполнены в одном стиле
  - пользователь должен иметь возможность менять nickname
  - интерфейс сайта должен быть понятным и простым в использовании
  - должна быть возможность смены языка 
  - игроки не должны иметь возможность внесения изменений в терминале соперника, копирования кода
